package com.yohan.event_planner.domain;

import jakarta.persistence.*;
import java.time.ZoneOffset;
import java.time.ZonedDateTime;
import java.util.Objects;

/**
 * Entity representing a scheduled event created by a user.
 *
 * <p>This entity supports core event functionality including event creation, start and end times,
 * timezone information, and optional event descriptions. It also tracks the creator of the event.</p>
 *
 * <h2>Timezone Handling</h2>
 * <ul>
 *     <li>Start and end times are internally stored in UTC for consistency.</li>
 *     <li>The original time zone IDs are stored separately to support conversion back to the user's zone.</li>
 * </ul>
 *
 * <p>This class focuses on persistence and encapsulated behavior.
 * Validation of input values and business rules should be handled by service or DTO layers.</p>
 */
@Entity
@Table(name = "events")
@Access(AccessType.FIELD)
public class Event {

    // region Fields

    /** Unique identifier for the event. Auto-generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Event's name or title. */
    @Column(nullable = false, length = 50)
    private String name;

    /** The user who created the event. */
    @ManyToOne
    @JoinColumn(name = "creator_id", nullable = false)
    private final User creator;

    /** The event's start time, stored in UTC. */
    @Column(nullable = false)
    private ZonedDateTime startTime;

    /** The event's end time, stored in UTC. */
    @Column(nullable = false)
    private ZonedDateTime endTime;

    /** Optional description of the event. */
    @Column(length = 255)
    private String description;

    /** Time zone ID of the start time. */
    @Column(nullable = false, length = 50)
    private String startTimezone;

    /** Time zone ID of the end time. */
    @Column(nullable = false, length = 50)
    private String endTimezone;

    // endregion

    // region Constructors

    /**
     * Protected no-args constructor required by JPA.
     * Should not be used directly.
     */
    protected Event() {
        this.creator = null;
    }

    /**
     * Constructs a new event with required core fields.
     *
     * @param name      the event name/title
     * @param startTime the local start time including zone, internally stored as UTC
     * @param endTime   the local end time including zone, internally stored as UTC
     * @param creator   the user creating the event
     */
    public Event(String name, ZonedDateTime startTime, ZonedDateTime endTime, User creator) {
        this.id = null;
        this.name = name;
        this.creator = creator;
        this.startTimezone = startTime.getZone().getId();
        this.endTimezone = endTime.getZone().getId();
        this.startTime = startTime.withZoneSameInstant(ZoneOffset.UTC);
        this.endTime = endTime.withZoneSameInstant(ZoneOffset.UTC);
    }

    // endregion

    // region Getters & Setters

    /**
     * Returns the unique identifier for the event.
     *
     * @return the event ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the name of the event.
     *
     * @return the name of the event
     */
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    /**
     * Returns the user who created the event.
     *
     * @return the creator of the event
     */
    public User getCreator() {
        return creator;
    }

    /**
     * Returns the start time of the event.
     *
     * @return the start time of the event in UTC
     */
    public ZonedDateTime getStartTime() {
        return startTime;
    }

    /**
     * Sets the start time of the event and updates the stored UTC and original timezone ID.
     *
     * @param startTime the new start time including zone
     */
    public void setStartTime(ZonedDateTime startTime) {
        this.startTimezone = startTime.getZone().getId();
        this.startTime = startTime.withZoneSameInstant(ZoneOffset.UTC);
    }

    /**
     * Returns the end time of the event.
     *
     * @return the end time of the event in UTC
     */
    public ZonedDateTime getEndTime() {
        return endTime;
    }

    /**
     * Sets the end time of the event and updates the stored UTC and original timezone ID.
     *
     * @param endTime the new end time including zone
     */
    public void setEndTime(ZonedDateTime endTime) {
        this.endTimezone = endTime.getZone().getId();
        this.endTime = endTime.withZoneSameInstant(ZoneOffset.UTC);
    }

    /**
     * Returns the description of the event.
     *
     * @return the description of the event
     */
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Returns the time zone ID of the start time.
     *
     * @return the time zone ID of the start time
     */
    public String getStartTimezone() {
        return startTimezone;
    }

    /**
     * Sets the time zone ID for the start time.
     *
     * @param startTimezone the new start time zone ID
     */
    public void setStartTimezone(String startTimezone) {
        this.startTimezone = startTimezone;
    }

    /**
     * Returns the time zone ID of the end time.
     *
     * @return the time zone ID of the end time
     */
    public String getEndTimezone() {
        return endTimezone;
    }

    /**
     * Sets the time zone ID for the end time.
     *
     * @param endTimezone the new end time zone ID
     */
    public void setEndTimezone(String endTimezone) {
        this.endTimezone = endTimezone;
    }

    // endregion

    // region Equality & Hashing

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Event event)) return false;
        if (id != null && event.id != null) {
            return id.equals(event.id);
        }
        return Objects.equals(name, event.name)
                && Objects.equals(startTime, event.startTime)
                && Objects.equals(endTime, event.endTime)
                && Objects.equals(creator, event.creator)
                && Objects.equals(startTimezone, event.startTimezone)
                && Objects.equals(endTimezone, event.endTimezone);
    }

    @Override
    public int hashCode() {
        return (id != null) ? id.hashCode()
                : Objects.hash(name, startTime, endTime, creator, startTimezone, endTimezone);
    }

    // endregion
}
