--
-- Cleaned PostgreSQL schema dump for Flyway
--

--
-- Name: events; Type: TABLE; Schema: public
--

CREATE TABLE public.events (
    creator_id bigint NOT NULL,
    endtime timestamp(6) with time zone NOT NULL,
    id bigint NOT NULL,
    starttime timestamp(6) with time zone NOT NULL,
    endtimezone character varying(50) NOT NULL,
    name character varying(50) NOT NULL,
    starttimezone character varying(50) NOT NULL,
    description character varying(255)
);

--
-- Name: events_id_seq; Type: SEQUENCE; Schema: public
--

ALTER TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: user_roles; Type: TABLE; Schema: public
--

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    role character varying(255) NOT NULL,
    CONSTRAINT user_roles_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'MODERATOR'::character varying, 'ADMIN'::character varying])::text[])))
);

--
-- Name: users; Type: TABLE; Schema: public
--

CREATE TABLE public.users (
    active boolean NOT NULL,
    deleted boolean NOT NULL,
    id bigint NOT NULL,
    firstname character varying(50) NOT NULL,
    lastname character varying(50) NOT NULL,
    username character varying(50) NOT NULL,
    email character varying(255) NOT NULL,
    hashedpassword character varying(255) NOT NULL,
    timezone character varying(255) NOT NULL
);

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Primary Keys and Unique Constraints
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);

--
-- Foreign Key Constraints
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT fk7ljm71n1057envlomdxcni5hs FOREIGN KEY (creator_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(id);
